project:
  type: website
  output-dir: docs

website:
  title: "The Plant-Pollinator European Metaweb"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ibartomeus/EUPollinationMetaweb
        text: GitHub
      - icon: twitter
        href: https://twitter.com/intent/tweet?related=github&text=The%20Plant-Pollinator%20European%20Metaweb&url=https%3A%2F%2Fibartomeus.github.io%2FEUPollinationMetaweb&hashtags=PunkEditors
    style: floating
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: results.qmd
        text: Metaweb
      - href: methods.qmd
        text: Methods
      - href: what_next.qmd
        text: What next? 
      - href: references.qmd
        text: References  
      

format:
  html:
    theme: lux #change it here if you don't like the electric pink https://quarto.org/docs/output-formats/html-themes.html e.g. minty
    #css: styles.css
    toc: true
    