---
title: "Methods"
format: html
editor: visual
---

## Taxonomy and Distribution

We extracted updated taxonomic information and distribution per European country form the following sources:

-   Bees and Butterflies: Reverte et al 2023 (https://resjournals.onlinelibrary.wiley.com/doi/10.1111/icad.12680)

-   Buterflies: Maes et al 2019 (https://link.springer.com/article/10.1007/s10841-019-00127-z) Data extracted from: https://www.gbif.org/dataset/f9af6ffd-febc-4626-b2e8-809b1c60fa01

-   Plants: Govaerts et al. The World Checklist of Vascular Plants, a continuously updated resource for exploring global plant diversity. Sci Data 8, 215 (2021). (https://doi.org/10.1038/s41597-021-00997-6). Data Extracted April 2023 (Govaerts R (ed.). 2023. WCVP: World Checklist of Vascular Plants. Facilitated by the Royal Botanic Gardens, Kew. \[WWW document\] URL http://sftp.kew.org/pub/data-repositories/WCVP/ \[accessed 20 April 2023\].) For plants we filtered European taxa only. NOte that the country division is coarse for countries recently changing its borders. Hence, for plants assigned to e.g. former Yugoslavia, we assumed they are present in all countries emerging from it. This is not optimal, but the best we can do.

Those are the primary taxon considered. Extinct and doubtful distributional data were removed. For plants a further cleaning can be done by plant family by subsetting only angiosperms, or families known to be insect pollinated.

Other taxa of pollinator insects such as Bombilids (<https://eunis.eea.europa.eu/species-taxonomic-browser.jsp?expand=46,648,699,2045,1172#level_1172> ; https://smujo.id/biodiv/article/view/3107; http://hbs.bishopmuseum.org/bombcat/bombcat2015.pdf) can be added if needed. Beetles, Wasps, and other Diptera are harder to track, as only a subset of those taxa are flower visitors. An approach would be to first see which families appear into the interactions database, and add those in the future. I think we should limit to diurnal pollinators as per data availability.

## Interaction Data

We compiled X datasets from X researchers of plant-pollinator networks.

Furthermore, we added X interactions contained in species occurrences, mostly deposited in museums.

Add data from Globi? Crops?

If you know of more sources that can be added, let us know.

## Analysis

We compiled everything and visualized\...

We can even revisit % of plants in Europe that are inscte pollinated (or visited).
